### PR TITLE
Add feature where a URL click results in a browser page being opened up

### PR DESCRIPTION
**Pull request by nswarup14**
**Updates**
In this feature, I have tried to implement a feature where one can click on a URL text using <Ctrl>+"Left
Mouse click", which open the link in the default browser of your system. The terminal now can recognise links and click on them.

**Files changed/added**
1) `terminal.py`
2) `vteterm.py`

I have tested it on Ubuntu 18.04 with Chrome browser as the default browse. I have yet to test on Browse-activity, which I shall be doing now. I wanted to see if the patch works other systems as well and receive feedback.

Thanks!

### CODE REVIEW

**Comment by pro-panda** [comment]
- set pep8 and flake8 fixes
- missing newline at end of file
- use imperative mood style for commits
- Write a shorted commit message,
```
Left click over hyperlink opens it in Browse Activity
<Insert one line summary of how did you implement this>
```

Make a checklist of such mistakes you make. Go through it before every PR you make.
@Aniket21Mathur as well.

**Comment by pro-panda** [comment]
Tested, didn't work.

 - opened terminal activity,
    - `cd terminal-activity`
    - `sugar-activity`
 - `echo https://www.github.com`
 - Hovered mouse over link. No change of cursor.
 - Clicked over link. No effect
 - `ctrl` + click over link. No effect

**Comment by nswarup14** [comment]
@pro-panda 
Thanks
For testing I used this `printf '\e]8;;http://example.com\e\\This is a link\e]8;;\e\\\n'`, which was found here https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda, which was recognised by the activity.

And regarding the test method, what I did was copy/paste `printf '\e]8;;http://example.com\e\\This is a link\e]8;;\e\\\n'`, in the activity and `ctrl+left click` on the link displayed, to open it in the chrome browser (default browser on my UBuntu system is 18.04)

Tested on Ubuntu 18.04 Sugar v0.114

**Comment by quozl** [comment]
https://github.com/sugarlabs/terminal-activity/issues/27 has an outline of how to proceed.  I agree with @pro-panda, and have updated the issue.  Please separate out discussion; work on design on the issue, and implementation on a pull request.

**Comment by quozl** [comment]
Reviewed.  In addition to @pro-panda's observations above, I'd prefer it to be integrated into the `terminal.py` file rather than make a new class.  The comment on the first line of `vteterm.py` is strange to me; what did you mean by it?

**Comment by nswarup14** [comment]
@quozl 
The reason for creation of the new `vteterm.py` was so as to separate the logic for class creation vs the terminal-activity. The properties of the Vte widget (color, background, font etc) can be set in the new class, and the rest of activity can function whilst creating an instance of the new class. I feel this helps us to distinguish the control flow for the activity and the logic for the class.

Regarding the first comment, what I meant is that I wished to implement the feature correctly and completely leaving no room for bugs or error :D
I referred an existing terminal called [Guake](https://github.com/Guake/guake), for the feature implementation.

**Comment by quozl** [comment]
Okay, thanks.

Code gets messy.  In the code before your change, an instance of Vte.Terminal is created, customised, and tightly integrated into the methods of the activity class.  Yet the customisations are not moved to the new file you create.  So now to understand the Vte behaviour, two files have to be consulted.  Could the new class be in the `terminal.py` file?  Could the customisations in `_create_tab` and `_configure_vt` move into the new class?

I note Guake is licensed under GPLv2+, so is legally safe to use here.

**Comment by nswarup14** [comment]
Yes James, I was planning on moving `_create_tab` and `_configure_vt` to
the new class. Right now, the configuration of Vte terminal is done in two
files (partly in `terminal.py` and partly in `vteterm.py`). I shall update
the patch.

**Comment by quozl** [comment]
Tested.  Does not work properly, see [what is expected](https://github.com/sugarlabs/terminal-activity/issues/27), and please discuss anything about the user experience in the issue.

It is caused by how you configured _Vte.Terminal_.  Your call to [_match_check_event_](https://lazka.github.io/pgi-docs/Vte-2.91/classes/Terminal.html#Vte.Terminal.match_check_event) is always returning None.  In turn this is because [_match_add_regex_](https://lazka.github.io/pgi-docs/Vte-2.91/classes/Terminal.html#Vte.Terminal.match_add_regex) has not been called.  Call it after your call to _set_allow_hyperlink_.

See how [GNOME Terminal](https://github.com/GNOME/gnome-terminal/blob/master/src/terminal-screen.c#L363) does it, along with the [regular expressions](https://github.com/GNOME/gnome-terminal/blob/master/src/terminal-regex.c).

See how [Guake](https://github.com/Guake/guake/blob/5ab40924dc89745115356c861f5f627bd84b7220/guake/terminal.py#L194) does it, along with the [regular expressions](https://github.com/Guake/guake/blob/master/guake/globals.py#L77).

(Or perhaps long term we should embed GNOME Terminal into the activity.  I don't know how embeddable it is at the moment, but I see several packages that depend on GNOME Terminal, so it seems likely to be possible.  As long as it doesn't break anything or take too long to start.)

**Comment by quozl** [comment]
Thanks.  Reviewed 5f5bef0.  You appear to have placed test cases in the list `TERMINAL_MATCH_EXPRS`.  I don't think these are needed.

**Comment by nswarup14** [comment]
@quozl [ae597e9](https://github.com/sugarlabs/terminal-activity/pull/35/commits/ae597e9c7cb1868a84f6abbb023d5493ac7c27cd) now works in a Sugar environment, and on `<Ctrl> + left mouse click` opens `Browse-activity` with the right URL. The journal object is also created correctly. I have set the `mime_type` of the journal object as `text/uri-list`.

On the point of user experience, the current patch does not execute the `right mouse click`. The behavior for the same presently is nothing. Can you guide me how I should go about implementing the below mentioned feature:-
**Right-click on link shows menu with "Open Link" and "Copy Link" options for URLs, and "Open Hyperlink" and "Copy Hyperlink" options for link text**?

Thanks!

**Comment by quozl** [comment]
Thanks.  Tested 25196d5 on Ubuntu 18.04.  Terminal activity failed to start, and `org.laptop.Terminal-1.log` contains;

```log
Traceback (most recent call last):
  File "/usr/bin/sugar-activity", line 5, in <module>
    activityinstance.main()
  File "/usr/lib/python2.7/dist-packages/sugar3/activity/activityinstance.py", line 229, in main
    instance = create_activity_instance(activity_constructor, activity_handle)
  File "/usr/lib/python2.7/dist-packages/sugar3/activity/activityinstance.py", line 59, in create_activity_instance
    activity = constructor(handle)
  File "/usr/share/sugar/activities/Terminal.activity/terminal.py", line 154, in __init__
    self._create_tab(None)
  File "/usr/share/sugar/activities/Terminal.activity/terminal.py", line 350, in _create_tab
    vt = vteterm.Terminal(self)
  File "/usr/share/sugar/activities/Terminal.activity/vteterm.py", line 43, in __init__
    self.check_matches()
  File "/usr/share/sugar/activities/Terminal.activity/vteterm.py", line 49, in check_matches
    regex = Vte.Regex.new_for_match(expr, len(expr), 0)
GLib.Error: vte-regex-error: PCRE2 not supported (2147483647)
Exited with status 1, pid 1865 data (<open file '<fdopen>', mode 'w' at 0x7fa5f42504b0>, dbus.ByteArray('4d96f36eca917c8d29272f16bb8e39b77a85eb7e', variant_level=1))
```

* [ ] can it be made to work on Ubuntu 18.04, if so how?

Tested same on Ubuntu 19.04.  Terminal activity does start.  Logs contain three;
```log
(sugar-activity:2246): Vte-WARNING **: 11:20:48.119: (../../src/vtegtk.cc:1975):
    int vte_terminal_match_add_regex(VteTerminal*, VteRegex*, guint32):
    runtime check failed: (_vte_regex_get_compile_flags(regex) & PCRE2_MULTILINE)
```

* [ ] can this be removed?

On interaction with a displayed URL, the log contained;

```log
(sugar-activity:2246): Vte-WARNING **: 11:22:28.076: VteSelectionFunc callback ignored.
```

* [ ] can this be removed?

The <kbd>ctrl</kbd> click did work; Browse opened.  A journal object was created.  Browse logs were fine.  My suggestions;

* [ ] change the journal object title from "Browse Activity" to the URL, as you won't know for sure that the Browse Activity will be activated,
* [ ] change the description to "A URL shown by the Terminal Activity",
* [ ] do not create a journal object more than once for a URL; this may help to prevent multiple instances of Browse (test case; <kbd>ctrl</kbd>-click, <kbd>alt</kbd>+<kbd>tab</kbd>, <kbd>ctrl</kbd>-click, <kbd>F6</kbd>, count Browse instances)

Whether or not to implement the right-click feature is out of scope for the pull request, use the issue.

I'm happy to merge the <kbd>ctrl</kbd> click feature once the above log warnings and suggestions are responded to, and we'll keep the issue open.

How to implement the right-click feature is up to you; I suggest looking at other right-click menus in Sugar, and the GNOME Terminal sources.

Did not code review yet.

**Comment by nswarup14** [comment]
@quozl Thanks!
- [x] can it be made to work on Ubuntu 18.04, if so how?
So the reason for the error in 18.04 or 17.10 is because Ubuntu decided to roll back the PCRE changes for the Vte widget ([here](https://bugs.launchpad.net/ubuntu/+source/gnome-terminal/+bug/1666264 )).
So for it to work one might have to update their present `gnome-terminal` from 3.28 to 3.32 and above. This automatically updates Vte from 0.52 to 0.56. You can check your `gnome-terminal` version by running `gnome-terminal --version`.
This is because Ubuntu has decided to go forward with PCR2 from 19.04 (_Disco Dingo_), hence updated the terminal does the trick. 
http://changelogs.ubuntu.com/changelogs/pool/main/v/vte2.91/vte2.91_0.54.2-2ubuntu2/changelog
https://bugs.launchpad.net/ubuntu/+source/gnome-terminal/+bug/1666264
https://bugs.launchpad.net/ubuntu/+source/pcre3/+bug/1792544

- [x]  can this be removed?
Regarding `(sugar-activity:2246): Vte-WARNING **: 11:20:48.119: (../../src/vtegtk.cc:1975):
    int vte_terminal_match_add_regex(VteTerminal*, VteRegex*, guint32):
    runtime check failed: (_vte_regex_get_compile_flags(regex) & PCRE2_MULTILINE)`, I'm not entirely sure. It seems like an Ubuntu issue, or that's what most people seem to think (I googled around a bit and found several instances of similar errors which all point to Ubuntu reverting their PCRE2 support for Vte). 

- [x] can this be removed?
Regarding `(sugar-activity:2246): Vte-WARNING **: 11:22:28.076: VteSelectionFunc callback ignored`, I'm not entirely sure. The warning is listed out here,but I cant seem to trace the call to this function ([here](https://github.com/GNOME/vte/blob/master/src/vtegtk.cc))

I shall discuss the `right` click feature in the issue itself and the make the above changes you're requested.

Regarding duplicate Browse-activity instances, right now while the Journal object is being created, its not being reused. By clicking the link again I'm creating a new instance for the same URL and that causes duplication. I wish to enquire if this behaviour is expected or whether I should write a patch modifying it by querying existing Journal objects with the same URL and relaunching them?

Thanks

**Comment by quozl** [comment]
* [ ] files are left behind in the `instance` directory; these should be deleted after the journal object is created.

```log
guest@guest:~$ ls -l .sugar/default/org.laptop.Terminal/instance/
total 8
-rw-rw-r-- 1 guest guest 14 Jun  5 11:22 1559697747
-rw-rw-r-- 1 guest guest 14 Jun  5 11:41 1559698864
guest@guest:~$ █
```

**Comment by quozl** [comment]
>  * [x]  can it be made to work on Ubuntu 18.04, if so how?
>  So the reason for the error in 18.04 or 17.10 is because Ubuntu decided to roll back the PCRE changes for the Vte widget ([here](https://bugs.launchpad.net/ubuntu/+source/gnome-terminal/+bug/1666264)).
>  So for it to work one might have to update their present `gnome-terminal` from 3.28 to 3.32 and above. This automatically updates Vte from 0.52 to 0.56. You can check your `gnome-terminal` version by running `gnome-terminal --version`.

Thanks.  We cannot expect our users to update GNOME Terminal and Vte.  Can we instead change the code so that the feature is disabled if necessary support is unavailable, and yet still run the activity rather than fail to start?  If so, that's one less reason not to merge.

>  * [ ]   can this be removed?
>  Regarding `(sugar-activity:2246): Vte-WARNING **: 11:20:48.119: (../../src/vtegtk.cc:1975): int vte_terminal_match_add_regex(VteTerminal*, VteRegex*, guint32): runtime check failed: (_vte_regex_get_compile_flags(regex) & PCRE2_MULTILINE)`, I'm not entirely sure. It seems like an Ubuntu issue, or that's what most people seem to think (I googled around a bit and found several instances of similar errors which all point to Ubuntu reverting their PCRE2 support for Vte).

Thanks.  But this is on Ubuntu 19.04.  Do you get this warning?  On which operating system?

>  * [ ]  can this be removed?
>  Regarding `(sugar-activity:2246): Vte-WARNING **: 11:22:28.076: VteSelectionFunc callback ignored`, I'm not entirely sure. The warning is listed out here,but I cant seem to trace the call to this function ([here](https://github.com/GNOME/vte/blob/master/src/vtegtk.cc))

Thanks.  Looks likely to be something to do with our use of `Vte.Terminal.get_text` during activity stop, and you haven't changed that in this pull request.  A latent problem.

> Regarding duplicate Browse-activity instances, right now while the Journal object is being created, its not being reused. By clicking the link again I'm creating a new instance for the same URL and that causes duplication. I wish to enquire if this behaviour is expected or whether I should write a patch modifying it by querying existing Journal objects with the same URL and relaunching them?

It was my opinion; I didn't want a Journal object at all, and while I could accept just one, I got one for each click.  Ask on issue if a journal object is a welcome side-effect of the user experience?

**Comment by nswarup14** [comment]
Thanks!
- [x] Thanks. We cannot expect our users to update GNOME Terminal and Vte. Can we instead change the code so that the feature is disabled if necessary support is unavailable, and yet still run the activity rather than fail to start? If so, that's one less reason not to merge.

Yes, I have added a line that does this. At the moment, it is just a workaround. As mentioned in this comment ([here](https://github.com/sugarlabs/terminal-activity/pull/35#issuecomment-496800776)), it would be best to have one file, `terminal.py`, rather than having both `vteterm.py` and `terminal.py`.

- [x] Thanks. But this is on Ubuntu 19.04. Do you get this warning? On which operating system?
Yes, I do get the warnings. On Ubuntu 18.04. The reason I still get them is because for 18.04 and 17.04 (Bionic and Zesty), Ubuntu has chosen to remove PCRE2 from Vte, hence these flags are being shown. I was able to gather so much from googling quite a bit.

- [x] Thanks. Looks likely to be something to do with our use of Vte.Terminal.get_text during activity stop, and you haven't changed that in this pull request. A latent problem.
Yes, the warning is generated during activity stop, not related to the issue at hand. Shall I open a new issue for the same?

Regarding the issue for multiple journal instances, after testing I noticed that the activity is not storing the journal object correctly.
For example, on `ctrl + clicking` the link `https://github.com/sugarlabs`, a Browse-activity instance with the URL opens. However after navigating to different web pages from there, and then closing the activity, the instance is not safely correctly. When I click on the journal instance again, I am redirected to `https://github.com/sugarlabs`, instead of the page to which I navigated to earlier.

The default Browse-activity behaviour is that, after navigating to different web pages, it stores the last URL which was opened and on re-launching the activity the next time, the last seen webpage is displayed.

I spent time understanding what metadata the Browse-activity is saving everytime it is closed. However, I wasn't able to make much progress there as I'm storing almost the same details, yet the behaviour is different.

Thanks!

**Comment by quozl** [comment]
Briefly reviewed 1026106.  Datastore find can take a while on large journals.  If you also kept a dictionary of URL to journal object mapping, you'd avoid most of the calls to find.

**Comment by nswarup14** [comment]
@quozl Thanks
Where would I save such a dictionary mapping?

> Regarding the issue for multiple journal instances, after testing I noticed that the activity is not storing the journal object correctly.

I found out the reason for this. The `read_file` and `write_file` implementation for Browse-activity can be found [here](https://github.com/sugarlabs/browse-activity/blob/master/webactivity.py). There, the metadata stored when `mime_type == 'text/plain'` is different from when `mime_type=='text/uri-list'`.
I wanted to know what is the difference between the two `mime_types` and how Browse-activity is able to open a `mime_type = 'text/plain'`.
When I modified the present patch to set `mime_type = 'text/plain'`, and clicked on the URL link, Write-activity was launched instead of Browse-activity and the file displayed just contained the URL which I had written to it in the earlier step.

Thanks!

**Comment by quozl** [comment]
> @quozl Thanks
> Where would I save such a dictionary mapping?

Given the source code as it stands now, in the Terminal class in `vteterm.py`.

By the way, in Sugar coding style, the variables added to the instance by `__init__` would usually be prefixed with an underscore if the caller was not expected to use them.  Same goes for functions.

> > Regarding the issue for multiple journal instances, after testing I noticed that the activity is not storing the journal object correctly.
> 
> I found out the reason for the above issue. The `read_file` and `write_file` implementation for Browse-activity can be found [here](https://github.com/sugarlabs/browse-activity/blob/master/webactivity.py). There, the metadata stored when `mime_type == 'text/plain'` is different from when `mime_type=='text/uri-list'`.
> I wanted to know what is the difference between the two `mime_types` and how Browse-activity is able to open a `mime_type = 'text/plain'`.
> When I modified the present patch to set `mime_type = 'text/plain'`, and clicked on the URL link, Write-activity was launched instead of Browse-activity and the file displayed just contained the URL which I had written to it in the earlier step.

Yes, I understand there will be a different behaviour depending on how Browse was started.

**Comment by nswarup14** [comment]
> Yes, I understand there will be a different behaviour depending on how Browse was started.

Wouldn't that be an issue? There would different Browse-activity instances where the metadata stored, display is different.
Wouldn't it be ideal if Browse-activity instances opened via `ctrl+click` would be different from those opened through other ways.

Thanks.

**Comment by quozl** [comment]
Sugar wasn't designed from the start with activity being started by another activity, so we'll find some strange corner cases.  This is one of them.  Creating a journal object of type _text/uri-list_ was not in the user requirements, but was a technical necessity for launching Browse.  My opinion of ideal user experience is;
* if one does not yet exist, a journal object of type _text/uri-list_ is to be created for the link,
* the journal object is to be launched, resulting in Browse showing the URL,
* the user may follow links or open new tabs in Browse,
* Browse _replaces_ the journal object, in the usual fashion for a Browse session.

So after clicking on a link and visiting it in Browse, the net journal consequence should be as if the user had manually started Browse and pasted the link.

**Comment by pro-panda** [comment]
@nswarup14 ping

**Comment by srevinsaju** [comment]
@quozl Forgot to add fixes. This PR can be closed :/

**Comment by chimosky** [comment]
Fixed in #38.

**Pull request closed without merging**
