### PR TITLE
fixes Gdk.RGBA color parse error

### PR DESCRIPTION
**Pull request by Saumya-Mishra9129**
As Gdk.Color is deprecated , change to Gdk.RGBA is important. I have tested the activity is working as before.

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Tell me more about the problem you are fixing?  You said in the commit message that there was an error, but I'd like to understand more about it.

I've previously said that although Gdk.Color is deprecated, it has been deprecated for many years, and there's no sign of it going away yet.  We need to balance the effort against the need.  Lots of things are said to be deprecated in GTK, yet they are never followed up with removal.

Reviewing a86e45e;
* color_parse appears twice,
* color_parse is in a class method, instead of global scope; it is best to use class methods only when they are relevant to the class,
* the function returns a Gdk,RGBA, but the name of the function doesn't imply that, perhaps use `_to_rgba` as in Measure activity,
* the calls to ColorToolButton.set_color are validated in the toolkit with an `assert isinstance(color, Gdk.Color)`, and it seems to be important, thus;

```log
host:~$ python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from gi.repository import Gdk
>>> x = Gdk.RGBA()
>>> isinstance(x, Gdk.Color)
False
>>> 
```

**Comment by Saumya-Mishra9129** [comment]
Thanks @quozl for review. 
> color_parse appears twice

> color_parse is in a class method, instead of global scope; it is best to use class methods only when they are relevant to the class,

> the function returns a Gdk,RGBA, but the name of the function doesn't imply that, perhaps use _to_rgba as in Measure activity,
 
I should change the method signature as it is clashing with Gdk.color_parse().

> the calls to ColorToolButton.set_color are validated in the toolkit with an assert isinstance(color, Gdk.Color), and it seems to be important, thus;

As according to https://lazka.github.io/pgi-docs/Gdk-3.0/classes/Color.html , Gdk.Color is deprecated, we should also make changes in sugar-toolkit-gtk3 to avoid warning.

**Comment by chimosky** [comment]
Reviewed 4f203a4.

> I should change the method signature as it is clashing with Gdk.color_parse().

I don't understand what you meant here but hope this helps.
```
a = Gdk.RGBA()
>>> a.parse('black')
True
>>> a.to_color()
Gdk.Color(red=0, green=0, blue=0)
>>> type(a.to_color())
<class 'gi.overrides.Gdk.Color'>
>>> b = a.to_color()
>>> isinstance(b, Gdk.Color)
True
>>> 
```

Your next steps would be;
- [ ] create one instance of `_to_rgba` which would be in the global scope and not a class method.
- [ ] return `rgba.to_color()` in the defined `_to_rgba` function.

> As according to https://lazka.github.io/pgi-docs/Gdk-3.0/classes/Color.html , Gdk.Color is deprecated, we should also make changes in sugar-toolkit-gtk3 to avoid warning.

`Gdk.RGBA` requires floating point inputs between 0.0 and 1.0 for each colour component, whereas `Gdk.Color`accepts integers between 0x0 and 0xffff yes it's deprecated but it hasn't gone away.

**Comment by quozl** [comment]
> As according to https://lazka.github.io/pgi-docs/Gdk-3.0/classes/Color.html , Gdk.Color is deprecated, we should also make changes in sugar-toolkit-gtk3 to avoid warning.

Please, show us the warning.  I don't get a warning when I use Gdk.Color, so it must be something different about your test systems and mine.  I was hoping that the warning would be in the commit message.  In addition to the warning message now we also need to know more about why the warning happens for you and not for me.

Also, at exactly which point in execution does the warning occur?  At creation of a Gdk.Color, or at the time it is used?

A change of this nature to the toolkit could risk breaking the API for all activities, so some thought will have to be applied.  Will the function continue to accept Gdk.Color and Gdk.RGBA?

Also please test changing the foreground and background colours of the terminal.  Without testing that, the code path to `set_color` is not exercised.

**Comment by Saumya-Mishra9129** [comment]
> Please, show us the warning. I don't get a warning when I use Gdk.Color, so it must be something different about your test systems and mine. I was hoping that the warning would be in the commit message. In addition to the warning message now we also need to know more about why the warning happens for you and not for me

I faced the warning when Gdk.Color is used. But as sugar-toolkit is not yet ported to Gdk.RGBA, making changes here will not be good. But as in future, when Gdk.Color will be gone away, we then have to port all required activities to Gdk.RGBA. As there are  more activities ; Calculate, Chart, Develop, Distance, Log, Memorize, Paint, Record, Ruler, Stopwatch.

**Comment by Saumya-Mishra9129** [comment]
> Your next steps would be;
> 
> * [ ]  create one instance of `_to_rgba` which would be in the global scope and not a class method.
> * [ ]  return `rgba.to_color()` in the defined `_to_rgba` function.

@chimosky Thanks for reviewing. I will made changes as suggested by you.

**Comment by quozl** [comment]
Thanks, but I'm yet to see the warning message.  Please show us the warning message?  Please identify the version of operating system or GTK?  And what do you mean by "used"; is that an instantiation of an object from the class, or when passing the object to a function?  Can you reproduce the warning using Python REPL?

**Comment by quozl** [comment]
I'm not seeing this warning with _master_ on Ubuntu 20.04

**Comment by JuiP** [comment]
I agree with @quozl I could not see the warning. Tested on debian 10 buster (sugar live build)

**Comment by quozl** [comment]
Some of the code has changed, and there's a change the changes fixed this, so I'll close this pull request.

**Pull request closed without merging**
