### PR TITLE
[Fix] Help button not working.

### PR DESCRIPTION
**Pull request by chimosky**

### CODE REVIEW

**Comment by quozl** [comment]
Why was this closed?

**Comment by chimosky** [comment]
@Pro-Panda was [working](https://github.com/sugarlabs/terminal-activity/pull/24) on this, although he closed the pull request he made mention that he's still working on it to include the changes you requested. I closed when i noticed.

**Comment by quozl** [comment]
Thanks.  There's no need to wait for @Pro-Panda if you have a fix; it's the best fix that will win the merge.  But your fix was no different to https://github.com/sugarlabs/terminal-activity/pull/24/commits/1b3086d58231030733048577a8d290950814c074.  Please do work on it alone or together and fix the consequent problems shown in https://github.com/sugarlabs/terminal-activity/pull/24#issuecomment-365809789.  It's what I would do if I were working on the problem.

**Comment by Pro-Panda** [comment]
@chimosky, I was at fault here, Sorry. I lost track of my PR and forgot to update.
I am not working on it currently, so anyone can continue work on the same

**Comment by chimosky** [comment]
Okay.

**Pull request closed without merging**
