### PR TITLE
Erase Scroll Buffer

### PR DESCRIPTION
**Pull request by Hrishi1999**
Added feature from https://github.com/sugarlabs/terminal-activity/issues/32

### CODE REVIEW

**Comment by chimosky** [comment]
Tested, got this traceback.

```
Traceback (most recent call last):
  File "/usr/src/sugar-activities/Terminal.activity/terminal.py", line 655, in __clear_cb
    vt.feed_child('reset \n')
TypeError: Vte.Terminal.feed_child() takes exactly 3 arguments (2 given)
tes
Traceback (most recent call last):
  File "/usr/src/sugar-activities/Terminal.activity/terminal.py", line 655, in __clear_cb
    vt.feed_child('reset \n')
TypeError: Vte.Terminal.feed_child() takes exactly 3 arguments (2 given)
tes
Traceback (most recent call last):
  File "/usr/src/sugar-activities/Terminal.activity/terminal.py", line 655, in __clear_cb
    vt.feed_child('reset \n')
TypeError: Vte.Terminal.feed_child() takes exactly 3 arguments (2 given)
```

**Comment by quozl** [comment]
Thanks for trying.  Did you test?  Also;
* it won't work if the shell is suspended while a child process is running; e.g. python, because python doesn't know what reset means,
* there are better features of `Vte.Terminal` that could be used, please read the documentation for the class; there are two methods potentially suited to the requirement,
* adding it to the edit menu was suggested by https://github.com/sugarlabs/terminal-activity/issues/32 but you have added it to the main toolbar.

**Comment by Hrishi1999** [comment]
I did test. I didn't get `TypeError: Vte.Terminal.feed_child() takes exactly 3 arguments (2 given)`. 
There is reset method available, but for its proper working (in terminal activity), it needs to be followed by hitting the enter key or feeding a new line to Vte (which would again cause the error @chimosky faced).

**Comment by quozl** [comment]
Thanks.  Please both tell me what version of Vte you are using?  Vte has two versions, the version of the underlying library, and the version of the API.  I can't be specific about the latter without knowing operating system in use, but the former is probed by `terminal.py` in an exception handler, so you'll need to identify which line of code succeeds.

The `/usr/bin/reset` command you've suggested is wrong because it won't work if the shell isn't prompting, as I said in my first point.  Try entering Python first, you'll see what I mean.

Yes, I'm suggesting adding it to the edit toolbar.  Have you any better idea?

**Comment by Hrishi1999** [comment]
Library version : 0.52.2
Vte API version : 2.91

Yes, you are right. For example, as you said, if python is running, `reset` command won't work, nor Vte.reset() would. 
I have placed clear button in the edit toolbar.

**Comment by quozl** [comment]
> nor Vte.reset() would.

I'm puzzled by what you say.  How does `Vte.Terminal.reset()` not work?

**Comment by Hrishi1999** [comment]
If I am in the python shell, and use `reset()` it would clear the output, but won't reset the terminal, i.e it still will be in python shell

**Comment by quozl** [comment]
I'm obviously not getting through.  It is taking longer for me to talk to you than fix it myself, so here's what I suggest; https://github.com/sugarlabs/terminal-activity/commit/a5581b9a0a1878617718a9c15467b789f8af34ca.  Please review?

**Comment by Hrishi1999** [comment]
I tested your changes. It works as intended 😃. I got off the original problem and instead focussed on resetting the terminal instead of clearing scrollback buffer, my bad.

**Comment by quozl** [comment]
Thanks.  I've pushed it to your branch and thus the pull request.  Calling for review by others, now that we are co-authors.

**Comment by pro-panda** [comment]
Thanks, reviewed

**Pull request merged**
